  spring:
    h2.console:
      enabled: false

#    Wczesniej w pliku .properties wygadalo to tak:
#spring.h2.console.enabled=true
#spring.h2.console.path=/console
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.h2.console.settings.web-admin-password=sa
#spring.datasource.url=jdbc:h2:file:./too-db